[[server]]
local_addr = "127.0.0.1:9006"
password = "password"
method = "aes-128-cfb"

[[server]]
local_addr = "127.0.0.1:9007"
password = "password"
method = "aes-128-gcm"

[[server]]
local_addr = "127.0.0.1:9008"
password = "cCOgj5XnbkAoGKhaT/qBqA=="
method = "2022-blake3-aes-128-gcm"

[[server]]
local_addr = "temp.sock"
password = "password"
method = "aes-128-cfb"

[[server]]
local_addr = "127.0.0.1:9006"
password = "password"
method = "aes-128-cfb"
network = "udp"

[[client]]
local_addr = "127.0.0.1:6009"
server_addr = "127.0.0.1:9006"
password = "password"
method = "aes-128-cfb"

[[client]]
local_addr = "127.0.0.1:6010"
server_addr = "127.0.0.1:9007"
password = "password"
method = "aes-128-gcm"

[[client]]
local_addr = "127.0.0.1:6011"
server_addr = "127.0.0.1:9008"
password = "cCOgj5XnbkAoGKhaT/qBqA=="
method = "2022-blake3-aes-128-gcm"

[[client]]
local_addr = "temp.sock"
server_addr = "127.0.0.1:9006"
password = "password"
method = "aes-128-cfb"

[[redir]]
local_addr = "127.0.0.1:6010"
server_addr = "127.0.0.1:9006"
password = "password"
method = "aes-128-cfb"
network = "udp"
redir_addr = "127.0.0.1:8080"
